### ISSUE TITLE
OSError: [WinError 17] The system cannot move the file to a different disk drive.

### ISSUE THREAD

**Issue by andry81** [tsroten/fcache#28]
```
  File ... in <module>
    mycache.sync()
  File "c:\Python\x86\38\lib\site-packages\fcache\cache.py", line 183, in sync
    self._write_to_file(filename, self._buffer[ekey])
  File "c:\Python\x86\38\lib\site-packages\fcache\cache.py", line 249, in _write_to_file
    rename(tmp, filename)
  File "c:\Python\x86\38\lib\site-packages\fcache\posixemulation.py", line 95, in rename
    os.rename(src, dst)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\User\\AppData\\Local\\Temp\\tmp8nv5st6g' -> 'w:/...\\cache\\74657374'
```

**Comment by andry81** [comment]
I've tried a workaround from here: https://stackoverflow.com/questions/8858008/how-to-move-a-file-in-python/8858026#8858026

Replaced `os.rename` by `shutil.move` and has discovered a slowdown about `x50` times in the test from here: https://github.com/tsroten/fcache/issues/26

**Comment by andry81** [comment]
The reason for slowdown in the x100 retries on `_MoveFileEx` and `_MoveFileTransacted`. I removed the retries and code became `x100` times faster.

**Comment by andry81** [comment]
I've create respective patches here:
https://sourceforge.net/p/tacklelib/tacklelib/HEAD/tree/trunk/python_patches/fcache/

My wrapper to fix issues on the Windows:
https://sourceforge.net/p/tacklelib/tacklelib/HEAD/tree/trunk/python/tacklelib/tacklelib.cache.py

Tests:
https://sourceforge.net/p/tacklelib/tacklelib/HEAD/tree/trunk/python_tests/02_interactive/01_fcache_workarounds/

**Comment by Kronopt** [comment]
I've also come across this issue.
@tsroten are you planning on releasing a fix? Do you need help?
@andry81 can you provide a pull request?

**Comment by Kronopt** [comment]
I've been reading a bit, and `os.rename` can't move files across different drives in some cases [[docs.python.org](https://docs.python.org/3/library/os.html#os.rename)].

`shutil.move` on the other hand, does. Internally, `shutil.move` uses `os.rename` if the destination path is on the current filesystem, otherwise just copies the file and then deletes the original one [[docs.python.org](https://docs.python.org/3/library/shutil.html#shutil.move)].

`shutil.move` should be used instead of `os.rename`.

**Comment by andry81** [comment]
@Kronopt I don't have a fork, but you can just manually patch or replace the files using the links above.

**Comment by andkirby** [comment]
Found out to build a single command to apply @Kronopt 's patch. Maybe it would be useful in installation scripts.

```
curl -Ls https://github.com/Kronopt/fcache/commit/d72ceb103191e17d23c8cac8aa49a555ad39d017.patch 2>nul | git apply --directory=venv/Lib/site-packages "${@:2}"
```
where `venv/Lib/site-packages` is the path to a parent directory of the package `fcache`.
