### ISSUE TITLE
`FileCache.delete()` is not multiprocessing safe

### ISSUE THREAD

**Issue by jacob-indigo** [tsroten/fcache#42]
I'm sure it's not an extremely common use case but it is at least being used [this](https://github.com/Unleash/unleash-client-python/blob/feb7aa7ff3daf0878ee5584c84247d4a28f7103f/UnleashClient/__init__.py#L319) way with `unleash-client-python`. If you have multiple processes that all have their own instance of `FileCache` pointing at the same directory and they all try call `delete()` on shutdown, you'll always get one or more processes with a `FileNotFoundError` leaked from `shutil.rmtree`. 

In the best case, the first process that shutdowns will clean everything up and the other processes will error out. In the worst case, multiple processes will start deleting the cache concurrently and delete different parts of the cache and cause each other to error out, leaving the cache partially deleted. 

Example script to reproduce the family of errors:
```python
from multiprocessing import Process, Barrier
import hashlib

from fcache.cache import FileCache

N = 10

def worker(init_barrier, destroy_barrier):
    init_barrier.wait(timeout=5)
    cache = FileCache('demo')

    for i in range(1000):
        cache[str(i)] = i
    cache.sync()

    destroy_barrier.wait(timeout=5)
    cache.delete()

def main():

    init_barrier = Barrier(N)
    destroy_barrier = Barrier(N)

    procs = [Process(target=worker, args=(init_barrier, destroy_barrier), daemon=True) for n in range(N)]

    for proc in procs:
        proc.start()

    for proc in procs:
        proc.join()


if __name__ == '__main__':
    main()
```

That results in errors like this. The exact path that triggers the error varies between runs.
```
...
  File "/Users/xyz/demo/test-race-condition.py", line 17, in worker
    cache.delete()
  File "/Users/xyz/demo/fcache/src/fcache/cache.py", line 165, in delete
    shutil.rmtree(self.cache_dir, onerror=_on_error)
  File "/Users/xyz/.pyenv/versions/3.9.17/lib/python3.9/shutil.py", line 734, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/Users/xyz/.pyenv/versions/3.9.17/lib/python3.9/shutil.py", line 690, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Users/xyz/.pyenv/versions/3.9.17/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: '353239'
```

**Comment by tsroten** [comment]
This fix was released in [version 0.6.0](https://pypi.org/project/fcache/0.6.0/). Thanks again @jacob-indigo
